language: python

python:
  - 3.6

install:
  - pip install 'django==1.11.8'
  - pip install django-rest-framework
  - pip install djangorestframework-jwt
  - pip install Pillow
  - pip install 'xenon==0.5.4'
  - pip install django-ckeditor
  - pip install pytest pytest-django pytest-cov

script:
  - pytest

after_success:
  - pip install coveralls
  - coveralls
