# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_auto_20180118_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
